### ISSUE TITLE
p2p-Code-Review

### ISSUE THREAD

**Issue by ITurres** [Diegogagan2587/Leaderboard#4]
### ⭐Highlights⭐

✅ Descriptive commit history.
✅ A naming convention that promotes clarity and readability in class selectors.
✅ Well done using relative units.

#### Keep up the good work 🏆

---

## Team Suggested Changes ♻️

By @ITurres:

Kindly consider using a class to target the `button` directly instead of chaining selectors can provide more flexibility and maintainability to your code. It's generally considered a best practice to use classes for targeting specific elements whenever possible.

By adding a class to the `button`, you can easily reuse the styling in different contexts and have more control over the specific elements you want to style. Additionally, it improves the readability of your code and makes it easier to understand the purpose of the class.

From this:

```css
.add-score-container form button {
  margin-right: 0;
  margin-left: auto;
}
```

To: 

**e.g**

```css
.custom-button {
  margin-right: 0;
  margin-left: auto;
}
```

---
